<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net472</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <LangVersion>latest</LangVersion>
    <AssemblyName>AutoPrintAgent</AssemblyName>
    <RootNamespace>AutoPrintAgent</RootNamespace>
    <Version>1.0.0</Version>
    <Company>MaterialPull</Company>
    <Product>斑马标签自动打印代理</Product>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Deterministic>true</Deterministic>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="System.Web.Extensions" />
  </ItemGroup>

</Project>
